/* ProVend — autenticación y sesión del navegador */
const AUTH_KEY = 'ProVend_user';
const API_BASE = window.location.protocol === 'file:' ? 'http://localhost:3000' : '';

async function apiRequest(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, { credentials: 'include', ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } });
  const contentType = response.headers.get('content-type') || '';
  const data = contentType.includes('application/json') ? await response.json() : {};
  if (!response.ok) throw new Error(data.error || 'No se pudo completar la solicitud');
  return data;
}
function saveUser(user) { try { localStorage.setItem(AUTH_KEY, JSON.stringify(user)); } catch { /* almacenamiento no disponible */ } }
function normalizeUser(user) { return user ? { ...user, role: user.role || user.rol, name: user.name || user.nombre } : null; }
async function login(email, password) { try { const data = await apiRequest('/api/login', { method:'POST', body:JSON.stringify({ email:email.trim().toLowerCase(), password }) }); saveUser(data.user); return { success:true, user:normalizeUser(data.user) }; } catch (error) { return { success:false, error:error.message }; } }
async function register(data) { try { const result = await apiRequest('/api/register', { method:'POST', body:JSON.stringify({ nombre:data.name, email:data.email, password:data.password, rol:data.role, company:data.company, ruc:data.ruc, categoria:data.category }) }); saveUser(result.user); return { success:true, user:normalizeUser(result.user) }; } catch (error) { return { success:false, error:error.message }; } }
async function logout() { try { await apiRequest('/api/logout', { method:'POST' }); } finally { localStorage.removeItem(AUTH_KEY); window.location.href='index.html'; } }
function getCurrentUser() { try { const value=localStorage.getItem(AUTH_KEY); return value ? normalizeUser(JSON.parse(value)) : null; } catch { localStorage.removeItem(AUTH_KEY); return null; } }
function isLoggedIn() { return Boolean(getCurrentUser()); }
function requireAuth(redirectTo='login.html') { if (!isLoggedIn()) { window.location.href=redirectTo; return false; } return true; }
function getFavorites() { try { const value=localStorage.getItem('ProVend_favorites'); return Array.isArray(JSON.parse(value)) ? JSON.parse(value) : []; } catch { return []; } }
function isFavorite(providerId) { return getFavorites().includes(Number(providerId)); }
async function toggleFavorite(providerId) { const user=getCurrentUser(); if (!user || user.role !== 'empresa') { showToast('Inicia sesión como empresa para guardar favoritos','warning'); return false; } try { const method=isFavorite(providerId)?'DELETE':'POST'; await apiRequest(method==='POST'?'/api/favoritos':`/api/favoritos/${providerId}`, { method, body:method==='POST'?JSON.stringify({ proveedor_id:Number(providerId) }):undefined }); const favorites=getFavorites(); const index=favorites.indexOf(Number(providerId)); if(index>-1) favorites.splice(index,1); else favorites.push(Number(providerId)); localStorage.setItem('ProVend_favorites',JSON.stringify(favorites)); showToast(index>-1?'Eliminado de favoritos':'Agregado a favoritos','success'); return index===-1; } catch(error) { showToast(error.message,'error'); return isFavorite(providerId); } }
function showFieldError(fieldId,message) { const field=document.getElementById(fieldId); if(!field)return; field.classList.add('error'); let error=field.parentElement.querySelector('.form-error'); if(!error){error=document.createElement('span');error.className='form-error';field.parentElement.appendChild(error);} error.textContent=message; }
function clearFormErrors() { document.querySelectorAll('.form-input.error').forEach(el=>el.classList.remove('error')); document.querySelectorAll('.form-error').forEach(el=>el.remove()); }
function initLoginForm() { const form=document.getElementById('login-form'); if(!form)return; form.addEventListener('submit',async event=>{ event.preventDefault(); clearFormErrors(); const email=document.getElementById('login-email').value.trim(), password=document.getElementById('login-password').value; if(!email){showFieldError('login-email','El correo es requerido');return;} if(!password){showFieldError('login-password','La contraseña es requerida');return;} const result=await login(email,password); if(!result.success){showFieldError('login-email',result.error);showToast(result.error,'error');return;} const role=result.user.role; window.location.href=role==='admin'?'admin.html':role==='proveedor'?'dashboard-proveedor.html':'dashboard-empresa.html'; }); }
function initRegisterForm() { const form=document.getElementById('register-form'); if(!form)return; const options=document.querySelectorAll('.auth-type-option'); let selectedType=document.querySelector('.auth-type-option.selected')?.dataset.type||'proveedor'; const update=()=>{document.getElementById('fields-empresa').style.display=selectedType==='empresa'?'block':'none';document.getElementById('fields-proveedor').style.display=selectedType==='proveedor'?'block':'none';}; options.forEach(option=>option.addEventListener('click',()=>{options.forEach(item=>item.classList.remove('selected'));option.classList.add('selected');selectedType=option.dataset.type;update();})); update(); form.addEventListener('submit',async event=>{event.preventDefault();clearFormErrors();const name=document.getElementById('register-name').value.trim(),email=document.getElementById('register-email').value.trim(),company=document.getElementById(selectedType==='empresa'?'register-company-empresa':'register-company-proveedor').value.trim(),password=document.getElementById('register-password').value,ruc=document.getElementById('register-ruc')?.value.trim()||'',category=document.getElementById('register-category')?.value||'';if(name.length<2){showFieldError('register-name','Escribe un nombre válido');return;}if(!email){showFieldError('register-email','El correo es requerido');return;}if(company.length<2){showFieldError(selectedType==='empresa'?'register-company-empresa':'register-company-proveedor','El nombre es requerido');return;}if(selectedType==='proveedor'&&(!ruc||!category)){showToast('Completa RUC y categoría','warning');return;}if(password.length<6){showFieldError('register-password','Mínimo 6 caracteres');return;}if(!document.getElementById('register-terms')?.checked){showToast('Debes aceptar los términos de servicio','warning');return;}const result=await register({name,email,company,password,role:selectedType,ruc,category});if(!result.success){showToast(result.error,'error');return;}showToast('Cuenta creada exitosamente','success');setTimeout(()=>{window.location.href=selectedType==='proveedor'?'dashboard-proveedor.html':'dashboard-empresa.html';},500);});}
document.addEventListener('DOMContentLoaded',()=>{initLoginForm();initRegisterForm();});
window.ProVendAuth={apiRequest,login,register,logout,getCurrentUser,isLoggedIn,requireAuth,toggleFavorite,getFavorites,isFavorite};
